// ============================================================================
// MEMORY FACT STORE TRAIT
// Abstract interface for durable memory fact storage
// ============================================================================

use crate::error::{StoreError, StoreResult};
use async_trait::async_trait;
use serde_json::Value;
// Domain types live in `zbot-stores-domain`; re-export here so the
// trait surface keeps working for callers that import from this crate.
pub use zbot_stores_domain::{MemoryFact, StrategyFactInsert, StrategyFactMatch};

/// Aggregate counts across the memory subsystem. Returned by
/// `MemoryFactStore::aggregate_stats` for the `GET /api/memory/stats`
/// endpoint. Tables that aren't present in the backing store
/// (e.g. wiki, procedures) report `0` rather than erroring — the
/// trait contract is "best-effort snapshot".
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MemoryAggregateStats {
    /// `memory_facts` row count.
    pub facts: i64,
    /// `kg_episodes` row count (durable per-session episode log).
    pub episodes: i64,
    /// `procedures` row count.
    pub procedures: i64,
    /// `ward_wiki_articles` row count.
    pub wiki_articles: i64,
    /// `kg_goals` row count where `state = 'active'`.
    pub goals_active: i64,
}

/// Snapshot of ingestion / consolidation health for
/// `GET /api/memory/health`. Pending and running counts are reported
/// from the kg-episode lifecycle table; failed_recent counts the
/// `status='failed'` rows. Compaction metrics live on a separate
/// repository (`compaction_repo`) and are not part of this snapshot.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MemoryHealthMetrics {
    /// Episodes currently waiting in the pending queue.
    pub queue_pending: u64,
    /// Episodes currently running through extraction.
    pub queue_running: u64,
    /// Episodes that failed during extraction.
    pub failed_recent: u64,
}

/// One row in the per-skill staleness tracker. Lives in this dependency-light
/// trait crate so consumers can use it without dragging in the SQLite stack.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkillIndexRow {
    /// Skill identifier (directory name, after vault-wins dedup).
    pub name: String,
    /// `'vault'` or `'agent'` — diagnostic only, not a join key.
    pub source_root: String,
    /// Absolute path to `<root>/<name>/SKILL.md` as last indexed.
    pub file_path: String,
    /// `SKILL.md` mtime in seconds since the Unix epoch as last indexed.
    pub mtime_unix: i64,
    /// `SKILL.md` size in bytes as last indexed. Breaks ties when two
    /// edits within the same second produce different content.
    pub size_bytes: i64,
    /// DB write time of the row, seconds since the Unix epoch.
    pub last_indexed_unix: i64,
    /// Embedding-content schema version. The reindex diff treats any
    /// row whose stored version disagrees with the running code's
    /// `CURRENT_INDEX_FORMAT_VERSION` as "modified", forcing one
    /// re-embed pass after a content-format change.
    pub format_version: i64,
}

/// Identity of the embedding vector space used for a query embedding.
///
/// Backends that persist vectors can use this to fail closed when a caller
/// supplies a query vector generated by a different provider/model/profile even
/// if the dimensions happen to match.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmbeddingQueryIdentity {
    pub provider_type: String,
    pub model: String,
    pub dimensions: u32,
    pub prompt_profile: String,
    pub normalization: Option<String>,
}

/// Execution provenance supplied when a tool writes a durable memory fact.
///
/// The legacy [`MemoryFactStore::save_fact`] method predates ward-scoped
/// memory. This additive request lets backends that support richer scope
/// semantics persist the current session, ward, and stable writer source
/// without breaking existing store implementations.
#[derive(Debug, Clone, PartialEq)]
pub struct MemoryFactWriteRequest {
    pub agent_id: String,
    pub category: String,
    pub key: String,
    pub content: String,
    pub confidence: f64,
    pub session_id: Option<String>,
    pub ward_id: Option<String>,
    pub source_ref: Option<String>,
    pub valid_from: Option<chrono::DateTime<chrono::Utc>>,
}

/// Abstract interface for durable memory fact storage.
///
/// Implementations can wrap a database (SQLite via `MemoryRepository`),
/// a remote API, or an in-memory store for testing.
///
/// This trait lives here so `agent-tools` and `agent-runtime` can call DB
/// operations without depending on the concrete SQLite backend.
#[async_trait]
pub trait MemoryFactStore: Send + Sync {
    /// Save a structured fact to durable memory.
    ///
    /// On conflict (same agent_id + scope + key), updates content and bumps
    /// mention_count. Returns a JSON summary of the operation.
    ///
    /// `valid_from` records the bi-temporal "world time" at which the fact
    /// became true. When `Some(t)`, the implementation persists `t` on the
    /// row. When `None`, the implementation defaults to `Utc::now()`. Pass
    /// `None` for procedural / convention facts that have always been true.
    // Established signature: each field corresponds to a column on
    // `memory_facts`, so collapsing into a builder/struct would buy
    // little while breaking every existing call site.
    #[allow(clippy::too_many_arguments)]
    async fn save_fact(
        &self,
        agent_id: &str,
        category: &str,
        key: &str,
        content: &str,
        confidence: f64,
        session_id: Option<&str>,
        valid_from: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Value>;

    /// Save a fact together with the execution scope that produced it.
    ///
    /// The default preserves the legacy contract for stores that have not
    /// implemented ward/source provenance yet. Canonical semantic stores
    /// should override this method rather than dropping the supplied context.
    async fn save_fact_with_context(&self, request: MemoryFactWriteRequest) -> StoreResult<Value> {
        self.save_fact(
            &request.agent_id,
            &request.category,
            &request.key,
            &request.content,
            request.confidence,
            request.session_id.as_deref(),
            request.valid_from,
        )
        .await
    }

    /// Recall facts relevant to a query using hybrid search.
    ///
    /// Combines FTS5 keyword matching and vector cosine similarity
    /// (when embeddings are available). Returns a JSON array of results.
    async fn recall_facts(&self, agent_id: &str, query: &str, limit: usize) -> StoreResult<Value>;

    /// Recall facts with priority scoring applied (category weights, etc.).
    ///
    /// This is the upgraded version of `recall_facts` that applies the same
    /// priority engine used by system-level recall: corrections first,
    /// strategies second, user preferences third, etc.
    ///
    /// `as_of` enables point-in-time recall. When `Some(t)`, returns facts
    /// that were valid at time `t` (their `valid_from <= t < valid_until`).
    /// When `None`, returns currently-valid facts using `Utc::now()` as the
    /// cutoff. Pass `None` for the default "what is true now?" query.
    ///
    /// Default implementation falls back to `recall_facts`.
    async fn recall_facts_prioritized(
        &self,
        agent_id: &str,
        query: &str,
        limit: usize,
        as_of: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Value> {
        let _ = as_of;
        self.recall_facts(agent_id, query, limit).await
    }

    async fn recall_facts_prioritized_scoped(
        &self,
        agent_id: &str,
        query: &str,
        ward_id: Option<&str>,
        limit: usize,
        as_of: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Value> {
        let _ = ward_id;
        self.recall_facts_prioritized(agent_id, query, limit, as_of)
            .await
    }

    /// Exact-key lookup in the session-scoped ctx namespace.
    ///
    /// Returns the single row matching the ctx key, or `None` if absent.
    /// Unlike `recall_facts`, this is a precise lookup — no ranking, no
    /// fuzzy match. Used by subagents to fetch canonical session state
    /// (intent, prompt, plan, state.<exec_id>) by exact key.
    ///
    /// Default implementation returns `Ok(None)` for stores that don't
    /// support ctx storage.
    async fn get_ctx_fact(&self, _ward_id: &str, _key: &str) -> StoreResult<Option<Value>> {
        Ok(None)
    }

    /// Save a ctx-namespaced fact for the current session.
    ///
    /// Ctx facts use a fixed schema: `category='ctx'`, `scope='session'`,
    /// `agent_id='__ctx__'` (sentinel — not tied to any single agent),
    /// and the caller-supplied `ward_id` + `key`. The `owner` argument
    /// identifies who wrote the fact: `"root"` for session-canonical
    /// content (intent, prompt, plan) or `"subagent:<exec_id>"` for a
    /// subagent's handoff state.
    ///
    /// This method does NOT perform permission checks — those happen at
    /// the tool layer where the runtime knows if the caller is delegated.
    /// Ctx facts are excluded from fuzzy recall by default.
    ///
    /// Default implementation returns an error for stores that don't
    /// support ctx storage.
    async fn save_ctx_fact(
        &self,
        _session_id: &str,
        _ward_id: &str,
        _key: &str,
        _content: &str,
        _owner: &str,
        _pinned: bool,
    ) -> StoreResult<Value> {
        Err(StoreError::Unavailable(
            "ctx storage not implemented for this store".into(),
        ))
    }

    /// Upsert a ward-scoped primitive (function signature) extracted
    /// from a source file by the runtime's AST hook.
    ///
    /// Fixed schema: `category='primitive'`, `scope='global'`,
    /// `agent_id='__ward__'` (sentinel), caller-supplied `ward_id` +
    /// `key` (conventionally `primitive.<relative_path>.<symbol>`).
    /// `signature` is the one-line call form; `summary` is the first
    /// line of the function's docstring.
    ///
    /// Idempotent: re-extraction of the same symbol upserts in place.
    /// Ctx writes are cheap (no embedding generated) — primitives are
    /// queried by key + ward prefix, not by fuzzy similarity.
    ///
    /// Default implementation returns an error for stores that don't
    /// implement primitive storage.
    async fn upsert_primitive(
        &self,
        _ward_id: &str,
        _key: &str,
        _signature: &str,
        _summary: &str,
    ) -> StoreResult<Value> {
        Err(StoreError::Unavailable(
            "primitive storage not implemented for this store".into(),
        ))
    }

    /// List all primitives for a ward, grouped for ward-snapshot rendering.
    ///
    /// Returns an array of {key, signature, summary} ordered by key.
    /// Default implementation returns an empty array.
    async fn list_primitives(&self, _ward_id: &str) -> StoreResult<Value> {
        Ok(serde_json::json!({ "primitives": [] }))
    }

    /// Typed variant of `list_primitives` returning `Vec<MemoryFact>`.
    /// Used by the ward snapshot builder so it gets the raw key /
    /// content / source_summary triple without re-decoding the
    /// rendered JSON. Default returns empty.
    async fn list_primitives_for_ward(&self, _ward_id: &str) -> StoreResult<Vec<MemoryFact>> {
        Ok(Vec::new())
    }

    /// Recent `ctx.<session_id>.state.<exec_id>` rows for the given
    /// session, newest-first, capped at `limit`. Used by the ward
    /// snapshot builder to render the "prior steps this session"
    /// section. Default returns empty.
    async fn list_recent_state_handoffs(
        &self,
        _session_id: &str,
        _limit: usize,
    ) -> StoreResult<Vec<MemoryFact>> {
        Ok(Vec::new())
    }

    // =========================================================================
    // SKILL INDEX STATE
    // Per-skill staleness tracker for the incremental skill reindex.
    // Default implementations return empty / no-op, so stores that don't
    // care (mocks, in-memory) inherit safe behavior without code changes.
    // =========================================================================

    /// Delete every fact matching `(category, key)`. Used by the skill
    /// reindexer to clear ghost embeddings when a skill is removed from
    /// disk. Returns the number of rows deleted.
    async fn delete_facts_by_key(&self, _category: &str, _key: &str) -> StoreResult<usize> {
        Ok(0)
    }

    /// Read every row from the per-skill staleness tracker. Returns an
    /// empty Vec when the table is missing or empty (e.g. fresh DB).
    async fn list_skill_index(&self) -> StoreResult<Vec<SkillIndexRow>> {
        Ok(Vec::new())
    }

    /// Insert or replace one row in the per-skill staleness tracker.
    async fn upsert_skill_index(&self, _row: SkillIndexRow) -> StoreResult<()> {
        Ok(())
    }

    /// Delete a single row from the per-skill staleness tracker.
    async fn delete_skill_index(&self, _name: &str) -> StoreResult<bool> {
        Ok(false)
    }

    // =========================================================================
    // AGGREGATE / HEALTH METRICS (HTTP handlers)
    // Used by `GET /api/memory/stats` and `/api/memory/health`. Default
    // implementations return zeros so stores that don't track these
    // (mocks, in-memory) inherit safe behavior.
    // =========================================================================

    /// Aggregate counts across memory_facts, kg_episodes, procedures,
    /// ward_wiki_articles, and active kg_goals. Used by the memory
    /// stats endpoint. Default returns all zeros.
    async fn aggregate_stats(&self) -> StoreResult<MemoryAggregateStats> {
        Ok(MemoryAggregateStats::default())
    }

    /// Counts of pending / running / failed episodes for the memory
    /// health endpoint. Default returns all zeros.
    async fn health_metrics(&self) -> StoreResult<MemoryHealthMetrics> {
        Ok(MemoryHealthMetrics::default())
    }

    /// Count of all memory facts visible to `agent_id` (`Some`) or
    /// across all agents (`None`). Used by aggregate graph stats. The
    /// default returns `0`.
    async fn count_all_facts(&self, _agent_id: Option<&str>) -> StoreResult<i64> {
        Ok(0)
    }

    /// Paginated list of memory facts with optional `agent_id`, `category`,
    /// and `scope` filters. Returns each row as a `serde_json::Value` so
    /// that the trait surface stays free of concrete backend structs.
    /// Default returns empty.
    async fn list_memory_facts(
        &self,
        _agent_id: Option<&str>,
        _category: Option<&str>,
        _scope: Option<&str>,
        _limit: usize,
        _offset: usize,
    ) -> StoreResult<Vec<Value>> {
        Ok(Vec::new())
    }

    /// Typed variant of `list_memory_facts` returning `Vec<MemoryFact>`
    /// directly. Default deserialises the Value-based result so backends
    /// only need to implement `list_memory_facts`.
    async fn list_memory_facts_typed(
        &self,
        agent_id: Option<&str>,
        category: Option<&str>,
        scope: Option<&str>,
        limit: usize,
        offset: usize,
    ) -> StoreResult<Vec<MemoryFact>> {
        let rows = self
            .list_memory_facts(agent_id, category, scope, limit, offset)
            .await?;
        rows.into_iter()
            .map(|v| {
                serde_json::from_value(v)
                    .map_err(|e| StoreError::Invalid(format!("decode MemoryFact: {e}")))
            })
            .collect()
    }

    /// Fetch a single memory fact by id. Returns `None` if the row is
    /// absent. The shape mirrors the same JSON layout that
    /// `list_memory_facts` emits per row.
    async fn get_memory_fact_by_id(&self, _fact_id: &str) -> StoreResult<Option<Value>> {
        Ok(None)
    }

    /// Delete a single memory fact by id. Returns `true` if a row was
    /// removed, `false` if the id was absent.
    async fn delete_memory_fact(&self, _fact_id: &str) -> StoreResult<bool> {
        Ok(false)
    }

    /// Upsert a fully-shaped memory fact. The optional `embedding` is the
    /// L2-normalized name vector to persist alongside.
    /// Default returns an error so impls that don't support typed upsert
    /// fail loudly rather than silently dropping writes.
    async fn upsert_typed_fact(
        &self,
        fact: MemoryFact,
        embedding: Option<Vec<f32>>,
    ) -> StoreResult<()> {
        let _ = (fact, embedding);
        Err(StoreError::Unavailable(
            "upsert_typed_fact not implemented for this store".into(),
        ))
    }

    /// Access reinforcement: bump `mention_count` and set `last_accessed`
    /// on facts that made a final recall packet. Each retrieval slows the
    /// fact's recency decay (ACT-R base-level activation). Default is a
    /// no-op so backends that don't track access degrade silently.
    async fn touch_facts(&self, _fact_ids: &[String]) -> StoreResult<()> {
        Ok(())
    }

    /// Mark a fact as superseded by a newer fact. Both ids should already
    /// exist. `transition_time` is the moment at which the old fact stops
    /// being valid — typically `Utc::now()` for distillation paths, or the
    /// winner's `created_at` for bi-temporal conflict resolution where the
    /// system actually learned otherwise when the winning fact was recorded.
    /// Default returns no-op error so misuse is loud.
    async fn supersede_fact(
        &self,
        _old_id: &str,
        _new_id: &str,
        _transition_time: chrono::DateTime<chrono::Utc>,
    ) -> StoreResult<()> {
        Err(StoreError::Unavailable(
            "supersede_fact not implemented for this store".into(),
        ))
    }

    /// Mark a fact as archived (soft-delete). Used by sleep-time pruning.
    async fn archive_fact(&self, _fact_id: &str) -> StoreResult<bool> {
        Ok(false)
    }

    /// Hybrid FTS + vector search across memory facts. `mode` is one of
    /// `"fts"`, `"semantic"`, or `"hybrid"`. `query_embedding` is supplied
    /// only for semantic / hybrid modes (caller pre-embeds the query string).
    /// `ward_id` filters to a specific ward when set.
    /// Each row in the returned Vec carries a `match_source` field
    /// (`"fts"`, `"vec"`, `"hybrid"`) for downstream ranking display.
    ///
    /// `as_of` enables point-in-time recall. When `Some(t)`, returns facts
    /// that were valid at time `t` (their `valid_from <= t < valid_until`).
    /// When `None`, returns currently-valid facts using `Utc::now()` as the
    /// cutoff. Pass `None` for the default "what is true now?" query.
    // Established signature: each field corresponds to a search dimension;
    // collapsing into a builder would buy little while breaking every
    // existing call site.
    #[allow(clippy::too_many_arguments)]
    async fn search_memory_facts_hybrid(
        &self,
        _agent_id: Option<&str>,
        _query: &str,
        _mode: &str,
        _limit: usize,
        _ward_id: Option<&str>,
        _query_embedding: Option<&[f32]>,
        _as_of: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Vec<Value>> {
        Ok(Vec::new())
    }

    /// Identity-aware variant of `search_memory_facts_hybrid`.
    ///
    /// Backends that can validate embedding provenance should override this
    /// method. The default permits lexical/FTS-compatible calls, but fails
    /// closed for vector-backed semantic/hybrid calls so an implementation
    /// cannot silently discard `query_identity`.
    #[allow(clippy::too_many_arguments)]
    async fn search_memory_facts_hybrid_with_identity(
        &self,
        agent_id: Option<&str>,
        query: &str,
        mode: &str,
        limit: usize,
        ward_id: Option<&str>,
        query_embedding: Option<&[f32]>,
        query_identity: Option<&EmbeddingQueryIdentity>,
        as_of: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Vec<Value>> {
        if mode == "semantic" || (mode == "hybrid" && query_embedding.is_some()) {
            let _ = query_identity;
            return Err(StoreError::Unavailable(
                "embedding identity validation is not supported by this memory fact store".into(),
            ));
        }
        self.search_memory_facts_hybrid(
            agent_id,
            query,
            mode,
            limit,
            ward_id,
            query_embedding,
            as_of,
        )
        .await
    }

    /// Typed variant of `search_memory_facts_hybrid` returning
    /// `(MemoryFact, score, match_source)` tuples directly. Default
    /// deserialises the Value-based result so backends only need to
    /// implement `search_memory_facts_hybrid` (with `score` and
    /// `match_source` populated alongside the fact fields).
    ///
    /// `as_of` is threaded through to `search_memory_facts_hybrid` for
    /// point-in-time recall; see that method's docs for semantics.
    // Established signature: matches search_memory_facts_hybrid one-to-one
    // so the typed wrapper can pass everything through unchanged.
    #[allow(clippy::too_many_arguments)]
    async fn search_memory_facts_hybrid_typed(
        &self,
        agent_id: Option<&str>,
        query: &str,
        mode: &str,
        limit: usize,
        ward_id: Option<&str>,
        query_embedding: Option<&[f32]>,
        as_of: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Vec<(MemoryFact, f64, String)>> {
        self.search_memory_facts_hybrid_typed_with_identity(
            agent_id,
            query,
            mode,
            limit,
            ward_id,
            query_embedding,
            None,
            as_of,
        )
        .await
    }

    /// Identity-aware typed variant of `search_memory_facts_hybrid_typed`.
    #[allow(clippy::too_many_arguments)]
    async fn search_memory_facts_hybrid_typed_with_identity(
        &self,
        agent_id: Option<&str>,
        query: &str,
        mode: &str,
        limit: usize,
        ward_id: Option<&str>,
        query_embedding: Option<&[f32]>,
        query_identity: Option<&EmbeddingQueryIdentity>,
        as_of: Option<chrono::DateTime<chrono::Utc>>,
    ) -> StoreResult<Vec<(MemoryFact, f64, String)>> {
        let rows = self
            .search_memory_facts_hybrid_with_identity(
                agent_id,
                query,
                mode,
                limit,
                ward_id,
                query_embedding,
                query_identity,
                as_of,
            )
            .await?;
        rows.into_iter()
            .map(|mut v| {
                let score = v.get("score").and_then(|s| s.as_f64()).unwrap_or(0.0);
                let match_source = v
                    .as_object_mut()
                    .and_then(|o| o.remove("match_source"))
                    .and_then(|s| s.as_str().map(String::from))
                    .unwrap_or_else(|| "fts".to_string());
                let fact: MemoryFact =
                    serde_json::from_value(v).map_err(|e| format!("decode MemoryFact: {e}"))?;
                Ok((fact, score, match_source))
            })
            .collect()
    }

    // ---- Sleep-time synthesis (Phase D4) -------------------------------
    //
    // Reads/writes needed by the `Synthesizer` to dedup against
    // existing strategy facts and persist new ones. Default impls
    // return None / Err so backends that haven't implemented yet make
    // the synthesis cycle a quiet no-op rather than corrupting state.

    /// Find an existing strategy fact whose embedding's cosine
    /// similarity with `embedding` is at or above `threshold`. Scans
    /// up to `scan_limit` candidate facts in `category = "strategy"`
    /// for the agent. Default: no match.
    async fn find_strategy_fact_by_similarity(
        &self,
        _agent_id: &str,
        _embedding: &[f32],
        _threshold: f32,
        _scan_limit: usize,
    ) -> StoreResult<Option<StrategyFactMatch>> {
        Ok(None)
    }

    /// Identity-aware variant of [`MemoryFactStore::find_strategy_fact_by_similarity`].
    /// Stores that persist strategy embeddings should override this and fail
    /// closed when `query_identity` is missing or mismatched.
    async fn find_strategy_fact_by_similarity_with_identity(
        &self,
        agent_id: &str,
        embedding: &[f32],
        query_identity: Option<&EmbeddingQueryIdentity>,
        threshold: f32,
        scan_limit: usize,
    ) -> StoreResult<Option<StrategyFactMatch>> {
        let _ = query_identity;
        self.find_strategy_fact_by_similarity(agent_id, embedding, threshold, scan_limit)
            .await
    }

    /// Bump an existing strategy fact's `mention_count` and replace
    /// its `source_episode_id` with `merged_source_episode_id`.
    /// `now_rfc3339` is the timestamp to record under `updated_at`.
    /// Default: no-op error so misuse is loud.
    async fn bump_strategy_fact_episodes(
        &self,
        _fact_id: &str,
        _merged_source_episode_id: &str,
        _now_rfc3339: &str,
    ) -> StoreResult<()> {
        Err(StoreError::Unavailable(
            "bump_strategy_fact_episodes not implemented for this store".into(),
        ))
    }

    /// Insert a synthesised strategy fact. Returns the fact id used.
    /// The trait crate stays dep-light by taking a purpose-built
    /// `StrategyFactInsert` rather than a full `MemoryFact` struct
    /// (which lives in `zbot-stores-sqlite`). Default: no-op error.
    async fn insert_strategy_fact(&self, _req: StrategyFactInsert) -> StoreResult<String> {
        Err(StoreError::Unavailable(
            "insert_strategy_fact not implemented for this store".into(),
        ))
    }

    /// Get facts in a specific category for an agent, ordered by
    /// most-recently-mentioned. Used by the recall path for
    /// category-weighted augmentation (corrections, strategies, etc.)
    /// Default: empty.
    async fn get_facts_by_category(
        &self,
        _agent_id: &str,
        _category: &str,
        _limit: usize,
    ) -> StoreResult<Vec<MemoryFact>> {
        Ok(Vec::new())
    }

    /// Get all facts above a confidence threshold. Used by the recall
    /// path to surface "always relevant" durable knowledge regardless
    /// of query similarity. Default: empty.
    async fn get_high_confidence_facts(
        &self,
        _agent_id: Option<&str>,
        _threshold: f64,
        _limit: usize,
    ) -> StoreResult<Vec<MemoryFact>> {
        Ok(Vec::new())
    }

    /// Get a fact by its `(agent_id, scope, ward_id, key)` natural
    /// key. Used by the distillation pipeline to detect content
    /// changes and supersede prior facts. Default: None — backends
    /// without this lookup degrade to "always insert new" semantics.
    async fn get_fact_by_key(
        &self,
        _agent_id: &str,
        _scope: &str,
        _ward_id: &str,
        _key: &str,
    ) -> StoreResult<Option<MemoryFact>> {
        Ok(None)
    }

    // ---- Per-fact embeddings -------------------------------------------

    /// Return the stored embedding vector for a fact by its id, or `None`
    /// if no embedding has been indexed for it. Backends that keep
    /// embeddings in a side-table (e.g. sqlite-vec) implement this;
    /// others return the default `Ok(None)`.
    async fn get_fact_embedding(&self, _fact_id: &str) -> StoreResult<Option<Vec<f32>>> {
        Ok(None)
    }

    // ---- Embedding cache (best-effort optimization) ---------------------

    /// Read a cached embedding for `(content_hash, model_name)`.
    /// Backends may persist these to avoid re-embedding identical text.
    /// Default: None — caller falls back to live embedding generation.
    async fn get_cached_embedding(
        &self,
        _content_hash: &str,
        _model_name: &str,
    ) -> StoreResult<Option<Vec<f32>>> {
        Ok(None)
    }

    /// Persist an embedding under `(content_hash, model_name)` for
    /// future lookup. Best-effort; default no-op so backends without
    /// a cache table still build cleanly.
    async fn cache_embedding(
        &self,
        _content_hash: &str,
        _model_name: &str,
        _embedding: &[f32],
    ) -> StoreResult<()> {
        Ok(())
    }

    /// List memory facts for an agent, optionally filtered by scope.
    /// Used by the distillation pipeline to dedup against existing
    /// facts before upserting. Default: empty.
    async fn get_memory_facts(
        &self,
        _agent_id: &str,
        _scope: Option<&str>,
        _limit: usize,
    ) -> StoreResult<Vec<MemoryFact>> {
        Ok(Vec::new())
    }

    /// Distinct `source_episode_id` values from `memory_facts` rows where
    /// `contradicted_by IS NOT NULL` and `updated_at > since`. Used by
    /// the DecayEngine (MEM-001 Part A) to propagate contradictions from
    /// facts down to the KG entities and relationships that were
    /// extracted from the same episodes. NULL `source_episode_id`s and
    /// duplicates are dropped. Empty `since` (epoch) returns the full
    /// history. Default: empty so backends that haven't implemented
    /// yet just disable contradiction propagation.
    async fn list_contradicted_fact_episode_ids(
        &self,
        _agent_id: &str,
        _since: chrono::DateTime<chrono::Utc>,
    ) -> StoreResult<Vec<String>> {
        Ok(Vec::new())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::future::Future;
    use std::pin::Pin;
    use std::task::{Context, Poll, Waker};

    use serde_json::json;

    struct LegacyStore;

    #[async_trait]
    impl MemoryFactStore for LegacyStore {
        async fn save_fact(
            &self,
            _agent_id: &str,
            _category: &str,
            _key: &str,
            _content: &str,
            _confidence: f64,
            _session_id: Option<&str>,
            _valid_from: Option<chrono::DateTime<chrono::Utc>>,
        ) -> StoreResult<Value> {
            Ok(json!({"success": true}))
        }

        async fn recall_facts(
            &self,
            _agent_id: &str,
            _query: &str,
            _limit: usize,
        ) -> StoreResult<Value> {
            Ok(json!([]))
        }

        async fn search_memory_facts_hybrid(
            &self,
            _agent_id: Option<&str>,
            _query: &str,
            _mode: &str,
            _limit: usize,
            _ward_id: Option<&str>,
            _query_embedding: Option<&[f32]>,
            _as_of: Option<chrono::DateTime<chrono::Utc>>,
        ) -> StoreResult<Vec<Value>> {
            Ok(vec![json!({"id": "lexical"})])
        }
    }

    fn block_on_ready<F: Future>(future: F) -> F::Output {
        let mut cx = Context::from_waker(Waker::noop());
        let mut future = Box::pin(future);
        match Pin::as_mut(&mut future).poll(&mut cx) {
            Poll::Ready(output) => output,
            Poll::Pending => panic!("test future unexpectedly pending"),
        }
    }

    #[test]
    fn identity_aware_default_fails_closed_for_vector_backed_modes() {
        let store = LegacyStore;
        let identity = EmbeddingQueryIdentity {
            provider_type: "fastembed".to_string(),
            model: "test-model".to_string(),
            dimensions: 3,
            prompt_profile: "default".to_string(),
            normalization: Some("l2".to_string()),
        };
        let embedding = [0.1, 0.2, 0.3];

        let semantic = block_on_ready(store.search_memory_facts_hybrid_with_identity(
            Some("root"),
            "query",
            "semantic",
            5,
            None,
            Some(&embedding),
            Some(&identity),
            None,
        ));
        assert!(semantic.is_err());

        let hybrid = block_on_ready(store.search_memory_facts_hybrid_with_identity(
            Some("root"),
            "query",
            "hybrid",
            5,
            None,
            Some(&embedding),
            Some(&identity),
            None,
        ));
        assert!(hybrid.is_err());

        let fts = block_on_ready(store.search_memory_facts_hybrid_with_identity(
            Some("root"),
            "query",
            "fts",
            5,
            None,
            None,
            None,
            None,
        ))
        .expect("fts remains lexical");
        assert_eq!(fts.len(), 1);
    }
}
